#------- Select your Compier
#COMPTYPE="Cray"
#COMPTYPE="Intel"
COMPTYPE="GNU"
#COMPTYPE="PGI"

#------ Select known target machine
#SYSTYPE="Gordon"
#SYSTYPE="Stampede"
#SYSTYPE="BW"
SYSTYPE="Mac"
#SYSTYPE="Linux"

ifeq ($(SYSTYPE), "Mac")
CC			= gcc-5
MPICC		= mpicc
OMPFLAGS	= -fopenmp
LIBS		= -lm
endif

ifeq ($(SYSTYPE), "Gordon")
CC			= icc
MPICC		= mpicc
OMPFLAGS	= -openmp
LIBS		= -lm
endif

ifeq ($(SYSTYPE), "BW")
    ifeq ($(COMPTYPE), "Cray")
    CC			= cc
    MPICC		= cc
    OMPFLAGS	=
    LIBS		= -lm
    else ifeq ($(COMPTYPE), "GNU")
    CC          = gcc
    MPICC       = cc
    OMPFLAGS    = -fopenmp
    LIBS        = -lm
    endif
endif

ifeq ($(SYSTYPE), "Stampede")
CC          = icc
MPICC       = mpicc
OMPFLAGS    = -openmp
LIBS        = -lm
endif

mpi_greetings_1:
	$(MPICC) -o mpi_greetings_1.exe mpi_greetings_1.c
mpi_greetings_2:
	$(MPICC) -o mpi_greetings_2.exe mpi_greetings_2.c
matrix_mult_serial:
	$(CC) -o matrix_mult_serial.exe matrix_mult_serial.c
all:
	make clean
	make mpi_greetings_1 mpi_greetings_2 matrix_mult_serial

clean:
	rm -rf *.exe
